### ISSUE TITLE
Message doesn’t go to Telegram if the email adress contains underscore

### ISSUE THREAD

**Issue by hokoo** [hokoo/cf7-telegram#17]
[Support topic](https://wordpress.org/support/topic/message-doesnt-go-to-telegram-if-email-contains-underscore-_/)

**Comment by mezka** [comment]
Hello @hokoo than you for developing this awesome plugin. I'm experiencing this issue as well, been trying to look at debug.log in wordpress/wp-content but I can't find nothing logged, also been looking at the code (I'm not a PHP or wordpress developer) and can't find anything that looks wrong.

**Comment by mezka** [comment]
I've found this in my nginx error log:

PHP message: [TELEGRAM] Request has failed with error 400: Bad Request" while reading response header from upstream, client: 2800:810:4fe:83de:21f7:c8cf:8348:83b4, server: mesquita.com.ar, request: "POST /wp-json/contact-form-7/v1/contact-forms/6/feedback HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "mesquita.com.ar", referrer: "https://mesquita.com.ar/puertas-cortafuego-ignifugas/"
2024/05/16 00:11:14 [error] 2236320#2236320: *11 FastCGI sent in stderr: "PHP message: [TELEGRAM] Request has failed with error 400: Bad Request
PHP message: [TELEGRAM] Request has failed with error 400: Bad Request" while reading response header from upstream, client: 2800:810:4fe:83de:21f7:c8cf:8348:83b4, server: mesquita.com.ar, request: "POST /wp-json/contact-form-7/v1/contact-forms/6/feedback HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "mesquita.com.ar", referrer: "https://mesquita.com.ar/puertas-cortafuego-ignifugas/"
2024/05/16 00:13:36 [error] 2236320#2236320: *11 FastCGI sent in stderr: "PHP message: [TELEGRAM] Request has failed with error 400: Bad Request
PHP message: [TELEGRAM] Request has failed with error 400: Bad Request" while reading response header from upstream, client: 2800:810:4fe:83de:21f7:c8cf:8348:83b4, server: mesquita.com.ar, request: "POST /wp-json/contact-form-7/v1/contact-forms/6/feedback HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "mesquita.com.ar", referrer: "https://mesquita.com.ar/puertas-cortafuego-ignifugas/"
2024/05/16 00:15:42 [error] 2236320#2236320: *90 open() "/var/www/mesquita.com.ar/favicon.ico" failed (2: No such file or directory), client: 2001:bc8:1201:61f:569f:35ff:fe0f:ddec, server: mesquita.com.ar, request: "GET /favicon.ico HTTP/1.1", host: "www.mesquita.com.ar"

**Comment by hokoo** [comment]
@mezka 
I assume there's a mistake in markdown decoding. 
Perhaps, markdown supporting would be ceased in the future versions of the plugin.
